version: 0.3.0.{build}
branches:
  only:
    - master
skip_tags: true
skip_commits:
  files:
    - '**/*.md'
    - 'docs/*.*'
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - cmd: nuget restore
after_build:
  - ps: msbuild JsonComparer.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:Publish /property:ApplicationVersion="$env:APPVEYOR_BUILD_VERSION"
image: Visual Studio 2017
build:
  verbosity: minimal
artifacts:
  - path: JsonComparer.Console\bin\$(configuration)\app.publish
    name: JsonComparer.Console.ClickOnce
deploy:
  - provider: GitHub
    auth_token:
      secure: iXRTi0GXb0J+zxsiM3IBHjvGzHpn8Ml0bJSfjGrm/XQaL0LFb3RIKWEK/5j780/9
    artifact: JsonComparer.Console.ClickOnce
    draft: true
    force_update: true
    on:
      branch: master
