version: CI.{build}-{branch}
branches:
  except:
  - master
skip_tags: true
skip_commits:
  files:
    - '**/*.md'
    - 'docs/*.*'
configuration: Release
before_build:
- cmd: nuget restore
image: Visual Studio 2017
build:
  verbosity: minimal
