version: 1.0.0.{build}
branches:
  only:
    - master
skip_tags: true
skip_commits:
  files:
    - '**/*.md'
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - cmd: nuget restore
after_build:
  - ps: msbuild JsonComparer.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:Publish /property:ApplicationVersion="$env:APPVEYOR_BUILD_VERSION"
build:
  verbosity: minimal
artifacts:
  - path: JsonComparer.Console\bin\$(configuration)\app.publish
    name: Console.ClickOnce.App
